# Generated by Django 3.1 on 2020-08-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0007_auto_20200831_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='record_reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=20)),
                ('reviewer_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='record',
        ),
    ]
