# Generated by Django 3.1 on 2020-09-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0011_auto_20200901_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('question1', models.CharField(max_length=20)),
                ('question2', models.CharField(max_length=20)),
                ('question3', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='questions_answer',
        ),
    ]
