# Generated by Django 3.1 on 2020-09-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0012_auto_20200901_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='review_incentives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('reviewer_id', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=20)),
                ('coupon_code', models.CharField(max_length=20)),
            ],
        ),
    ]
