# Generated by Django 3.1 on 2020-09-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0013_review_incentives'),
    ]

    operations = [
        migrations.CreateModel(
            name='review_incentive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('reviewer_id', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('coupon_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='review_incentives',
        ),
    ]
