# Generated by Django 3.1 on 2020-10-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0016_record_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer_info',
            name='product_type',
            field=models.CharField(default='food', max_length=100),
        ),
    ]
