# Generated by Django 3.1 on 2020-10-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0017_reviewer_info_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_upload',
            name='product_type',
            field=models.CharField(default='sports', max_length=100),
        ),
    ]
