# Generated by Django 3.1 on 2020-10-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0018_image_upload_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_upload',
            name='question1',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='image_upload',
            name='question2',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='image_upload',
            name='question3',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='image_upload',
            name='question4',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='image_upload',
            name='question5',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='image_upload',
            name='question6',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='image_upload',
            name='question7',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='image_upload',
            name='question8',
            field=models.CharField(default='', max_length=300),
        ),
    ]
